### ISSUE TITLE
Using PicoCSS not TailwindCSS

### ISSUE THREAD

**Issue by ytsruh** [Luzefiru/hono-react-tailwind#1]
Hi. Firstly just wanted to say thanks for this, its helped me a bunch!

But also the repo is using PicoCSS and not TailwindCSS. Tailwind appears to work however as expected however the import of the PicoCSS appears to overide it

**Comment by Luzefiru** [comment]
Hello @ytsruh! 👋

I appreciate the feedback and I apologize for leaving PicoCSS in this repository. I was using this project initially for demo purposes, but I'm glad that it's being used by someone else.

I merged a PR to address your issues [here](https://github.com/Luzefiru/hono-react-tailwind/pull/2).

Thanks again for letting me know! Feel free to request for any other changes.
